blank_issues_enabled: false
contact_links:
  - name: Current Version
    url: https://play.google.com/store/apps/details?id=com.mrayush.calculator
    about: You can check our it's current version of the code here.